### ISSUE TITLE
Не работает открытие из файла

### ISSUE THREAD

**Issue by danchdanchdanch** [vit1251/liblex#1]
Привет! Спасибо за библиотеку, но как-то она не работает, если читать из файла. 
Приклепляю файлы, код примера и скриншот.

https://gist.github.com/danchdanchdanch/7d0fb0462b4537368fb60ad32bf67754

![2017-11-10 12 29 10](https://user-images.githubusercontent.com/5562992/32651650-c77b37a0-c612-11e7-91f4-9c5c15f3bf90.png)

[hi.lex.zip](https://github.com/lexview/liblex/files/1460821/hi.lex.zip)

**Comment by vit1251** [comment]
Хорошо вечером посмотрю и немного переделаю API уже давно хотел изменить,
но суть как была так и осталась.

Для получения следующего события из файла .LEX нужно передать структуру,
которая будет заполнена парсером.

Сейчас не помню, но существует несколько видов событий:

- Картинка (IMAGE или BITMAP)
- Буква (CHAR)
- Смена шрифта (CH_FONT)
- Смена междустрочного интервала (CH_LINE_WIDTH)

Соответственно код чтения примерно такой:

```
    int err = 0;
    struct parser *p;
    struct parser_event event;

    /* Open parser */
    err = parser_create( &p, "1.lex" );
    if (err) {
        goto out;
    }

  /* Reading */
  for (;;) {
      err = parser_read_next( p, &event );
      if ( err ) { /* По окончанию файла будет сгенерен EEOF */
          goto out;
      }
      render_event( event );
   }

    err= parser_destroy( p );

  out:

    if (err) {
      fprintf(stderr, "error: Internal error: code = %d", err);
    }
    return err;

```

Дальше получив сообщение или событие о событии можно подготавливать изображение на странице или в PDF или на Canvas.

**Comment by danchdanchdanch** [comment]
Это видимо код чтения для нового API? В старом функция `parser_create()` принимает один аргумент, да и функции` parser_read_next()` нет

**Comment by vit1251** [comment]
Писал по памяти. Да, действительно там на callback все организовано.
Пример лежит в example.
Символы в виде вопросов, так как Lexicon 1.2 работал в раскладке символов cp866 и нужно их декодировать в текущую локаль Mac OS. Я предполагаю, что UTF-8. Это можно сделать командой:

```
# ./example1 > 1.txt
# iconv -f cp866 -t utf8 < 1.txt > 2.txt
# cat 2.txt
```

**Comment by danchdanchdanch** [comment]
[log.txt](https://github.com/lexview/liblex/files/1463608/log.txt)

**Comment by vit1251** [comment]
Ну выглядит так как будто файл прочитан и выданы из него руны (символы).
Теперь можно заменить реакцию в примере на свой ренедер (например вывод в PDF или куда нужно) и использовать по своему усмотрению.

Задачу закрываем? Или остались еще вопросы?

**Comment by danchdanchdanch** [comment]
Как эти вопросы перевести в символы?

**Comment by vit1251** [comment]
Ну строго говоря цель библиотеки предоставить возможность разбора формата файла Lexicon, а все дальнейшие действия такие как обработка и рендеринг уже лежит на плечах потребителя. Исходный формат по дизайну(!) использует CP866 и это может быть удобно в некоторых случаях. Например, в xlexview использованы шрифты из поставки Lexicon и они так же в CP866.

Если нужно производить конвертацию, то можно использовать простое отображение (map) или воспользоваться библиотекой iconv, так как это стандартный конвертер в мире GNU. Более подробно можно узнать на страницах документации или посмотреть пример по ссылке http://www.gnu.org/software/libc/manual/html_node/iconv-Examples.html

**Comment by danchdanchdanch** [comment]
Не получается, все файлы перекодировал в UTF-8 iconv, они уже даже открывают обычным текстовым редактором, а вопросы все равно появляются. Не могу понять, это отсутствует что-то из таблицы символов или как?

**Comment by vit1251** [comment]
Исходный файл **hi.lex** по определению(!) должен быть в формате CP866 и он такой и был вначале обсуждения. В результате работы чтения Вы получаете события с символами и они закодированы по прежнему в CP866. Если нужно их отображение на экране консоли с локалью UTF-8, то нужно произвести конвертацию символа CP866 в UTF-8. Пример команды я приводил выше.

**Comment by danchdanchdanch** [comment]
Спасибо, можно добавить это к библиотеке 👍

**Comment by vit1251** [comment]
Если кратко, то нет.

Задача библиотеки прочитать и разобрать события файла в формате Lexicon, а дальнейшая обработка это личное дело потребляющей программы. Хотите мы можем создать отдельный проект конвертора Lexicon в обычный TXT формат, но я в этом вижу мало практической пользы, так как основная ценность формата в возможности использовать математические символы и знаки интеграла после конвертации эти сомволы скорее всего будут выглядеть иначе.

**Comment by danchdanchdanch** [comment]
Понял, unix-way
Я больше смотрю с прикладной стороны. Библиотеку хочу использовать как раз в своем проекте, только можно не в txt, а какой-нибудь rich text :)

**Comment by vit1251** [comment]
В целом тут все зависит от Вас если Вы умеете и знакомы с целевым форматом, то можно в RTF. Почитайте спецификацию и скажите сможете написать рендерер для RTF самостоятельно или возможно есть уже готовый librtf?

**Comment by vit1251** [comment]
Я так думаю, что с исходным вопросом "Не работает открытие из файла" мы разобрались? Можно закрывать данную задачу?

**Comment by danchdanchdanch** [comment]
Да, закрываем)
